In [2]:
###install.packages("tidygenomics")
#install.packages("dplyr")
#install.packages("fuzzyjoin")
#install.packages("readxl")
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install("IRanges")

also installing the dependencies ‘pkgconfig’, ‘purrr’, ‘generics’, ‘magrittr’, ‘R6’, ‘tibble’, ‘tidyselect’


Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

also installing the dependencies ‘lattice’, ‘stringi’, ‘cpp11’, ‘sp’, ‘stringdist’, ‘stringr’, ‘tidyr’, ‘geosphere’


Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

also installing the dependencies ‘rematch’, ‘hms’, ‘prettyunits’, ‘cellranger’, ‘Rcpp’, ‘progress’


Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [5]:
#library(tidygenomics)
library(dplyr)
library(fuzzyjoin)
library(readxl)
library(IRanges)

Loading required package: BiocGenerics

Loading required package: parallel


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:dplyr’:

    first, rename


The following objects are masked from ‘package:base’:

    expand.grid, I, unname



Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice

In [48]:
## Read in tables with identified germinal Mu insertions; 
germinal_ins <- read.csv("../../results/insertions_table_final/germinal_insertions.csv", header=TRUE)

## Read in stock matrix
MY_STOCK <- list.files("../../config/stock_matrix/", pattern="\\.xlsx$")
stock <- as.data.frame(read_excel(paste0("../../config/stock_matrix/", MY_STOCK)))
names(stock)[1] <- "X__1"
rownames(stock) <- stock$X__1
stock <- stock[, -1]
stock <- as.matrix(stock)

#grid table - to associate arbitrary names with row/col
grid_table <- read.csv("../../config/grid_sample_sheet.tsv", sep = "\t", header=TRUE)
grid_table <- grid_table %>%
                select(dim, base_name)

## Read Annotation File
#setwd("../FGS/")
#MY_gff3 <- list.files(getwd(), pattern="\\.gff3$")
annotation <- read.delim("../../resources/final_annotation_table", header=FALSE, comment.char="#")
# add column names
colnames(annotation) <- c("GeneID", "Chr", "Start", "End")

# reduce genes to ONE entry which is the longest
# multiple entries per gene likely, since after gffread, transcripts of different lengths are included (share name)
# we find the min and max positions (start & end coordinate with greatest distance) per gene and keep this record  
annotation <- annotation %>%
  group_by(GeneID, Chr) %>%
  summarise(Start = min(Start), End = max(End))

# compute gene_length
annotation <- annotation %>% 
  mutate(Gene_length = End - Start + 1)


# relocate Gene column before gene_length
#annotation <- annotation %>%
#  relocate(Gene, .before = gene_length)

New names:
* `` -> ...1

`summarise()` has grouped output by 'GeneID'. You can override using the `.groups` argument.

In [33]:
head(germinal_ins)
head(grid_table)
head(annotation)
nrow(annotation)

  Chr Start   End     Sample StartReads EndReads
1 1    971410  971418 Col-01  2          3
2 1   2113392 2113400 Col-01  7         17
3 1   3772030 3772038 Col-01 11          5
4 1   4340109 4340117 Col-01  8          2
5 1   4736284 4736292 Col-01 24         16
6 1   7558710 7558718 Col-01  5         10

  dim num base_name fq_1_file      fq_2_file      fq_1_end fq_2_end
1 row 1   Row-01    Row-01_1.fq.gz Row-01_2.fq.gz _1.fq.gz _2.fq.gz
2 row 2   Row-02    Row-02_1.fq.gz Row-02_2.fq.gz _1.fq.gz _2.fq.gz
3 row 3   Row-03    Row-03_1.fq.gz Row-03_2.fq.gz _1.fq.gz _2.fq.gz
4 row 4   Row-04    Row-04_1.fq.gz Row-04_2.fq.gz _1.fq.gz _2.fq.gz
5 col 1   Col-01    Col-01_1.fq.gz Col-01_2.fq.gz _1.fq.gz _2.fq.gz
6 col 2   Col-02    Col-02_1.fq.gz Col-02_2.fq.gz _1.fq.gz _2.fq.gz

  GeneID          Chr Start    End      Gene_length
1 ENSRNA049437471 1    2815814  2815887 74
2 ENSRNA049437473 1    2998702  2998773 72
3 ENSRNA049437518 1    5888817  5888890 74
4 ENSRNA049437607 1   10109832 10109903 72
5 ENSRNA049437614 1   10573120 10573190 71
6 ENSRNA049437658 1   18379795 18379867 73

[1] 46430

In [49]:
# join MuGerminal table with annotation
germinal_ins_annotated <- fuzzyjoin::genome_inner_join(germinal_ins, 
                                annotation, 
                                by=c("Chr", "Start", "End") 
                                )
head(germinal_ins_annotated)

  Chr.x Start.x  End.x    Sample StartReads EndReads GeneID         Chr.y
1 1      2113392  2113400 Col-01  7         17       Zm00001d027296 1
2 1      4736284  4736292 Col-01 24         16       Zm00001d027412 1
3 1      7558710  7558718 Col-01  5         10       Zm00001d027532 1
4 1     15014601 15014609 Col-01  4          2       Zm00001d027845 1
5 1     15014626 15014634 Col-01  2          7       Zm00001d027845 1
6 1     21998842 21998850 Col-01 23         13       Zm00001d028073 1
  Start.y  End.y    Gene_length
1  2109189  2113478  4290
2  4724456  4736832 12377
3  7558685  7564087  5403
4 15013950 15018699  4750
5 15013950 15018699  4750
6 21990180 22006881 16702

In [50]:
# rename, relocate and drop the columns to create a useful table
germinal_ins_annotated <- germinal_ins_annotated %>%
  dplyr::rename(
    Chr = Chr.y,
    Start = Start.y,
    End = End.y,
    InsertionStart = Start.x,
    InsertionEnd = End.x,
  ) %>%
  relocate(
    Sample, InsertionStart, InsertionEnd, StartReads, EndReads, .before = Gene_length
  ) %>%
  select(
    -Chr.x
  )

In [53]:
germinal_ins_grid_info <- merge(germinal_ins_annotated, grid_table, by.x = "Sample", by.y = "base_name")

# order the table as to have intersecting samples next to one another
germinal_ins_grid_info <- germinal_ins_grid_info %>%
  arrange(., Chr, Start, InsertionStart)


## assigning Stock
#create seperate dataframes - just with Cols and just with Rows
just_row <- germinal_ins_grid_info %>%
  filter(dim == "row") %>%
  select(-dim)
  
just_col <- germinal_ins_grid_info %>%
  filter(dim == "col") %>%
  select(-dim)

full <- c()
for (i in 1:nrow(just_row))  {
  full[i] <- stock[cbind(just_row$Sample[i], just_col$Sample[i])]
}

just_col$stock <- full
just_row$stock <- full

germinal_ins_annotated_stocks <- rbind(just_row, just_col)

# order the table as to have intersecting samples next to one another; again..
germinal_ins_annotated_stocks <- germinal_ins_annotated_stocks %>%
  arrange(., Chr, Start, InsertionStart) %>%
  relocate(Sample, .before = InsertionStart)


head(germinal_ins_annotated_stocks, n=10)

   GeneID         Chr Start   End     Sample InsertionStart InsertionEnd
1  Zm00001d027296 1   2109189 2113478 Row-01 2113392        2113400
2  Zm00001d027296 1   2109189 2113478 Col-01 2113392        2113400
3  Zm00001d027320 1   2878535 2889452 Row-03 2889029        2889037
4  Zm00001d027320 1   2878535 2889452 Col-04 2889029        2889037
5  Zm00001d027321 1   2883539 2892612 Row-03 2889029        2889037
6  Zm00001d027321 1   2883539 2892612 Col-04 2889029        2889037
7  Zm00001d027324 1   2959502 2972168 Row-01 2959609        2959617
8  Zm00001d027324 1   2959502 2972168 Col-04 2959609        2959617
9  Zm00001d027344 1   3371324 3374866 Row-02 3372136        3372144
10 Zm00001d027344 1   3371324 3374866 Col-03 3372136        3372144
   StartReads EndReads Gene_length stock
1  15         12        4290       D-0078
2   7         17        4290       D-0078
3   5          4       10918       D-0129
4   2          2       10918       D-0129
5   5          4        9074       D-0129
6   2          2        9074       D-0129
7   7         11       12667       D-0081
8  25         72       12667       D-0081
9  11          8        3543       D-0104
10  6         12        3543       D-0104

In [54]:
#setwd("MuSeq_table_final/")
write.csv(germinal_ins_annotated_stocks, 
          "../../results/insertions_table_final/germinal_identified_insertions_annotated.csv", 
          row.names=F)

In [178]:
nrow(MuGerminal_annotated)
#head(MuGerminal_annotated)

old_table <- read.csv("MuSeq_table_final/Mu_single_GeneIds_gene_lengths_and_stock.csv")
nrow(old_table)
head(old_table)


old_table  %>%
  filter(grepl('RNA', GeneID))


diff_vec <- setdiff(MuGerminal_annotated_stocks$InsertionStart, old_table$Start)
MuGerminal_annotated %>%
  filter(InsertionStart %in% diff_vec)

## apparently in the old approach I missed those insertions,
## which were overlapping with the borders of the gene model
## for this test set = 40..
## well, doesn't matter now I gues - or could I rerun and update
## probablyy not worth the work - although a master student could do it ;D

#test %>%
#  filter(grepl('B73', Chr.x))

[1] 2334

[1] 2254

  GeneID             Chromosome   Start    End      Sample StartReads EndReads
1 ENSRNA049997441-T1 7            39887977 39887985 Row-01  8          9
2 ENSRNA049997441-T1 7            39887977 39887985 Col-04 28         39
3 Zm00001d000035     B73V4_ctg182   387130   387138 Row-01  8          7
4 Zm00001d000035     B73V4_ctg182   387130   387138 Col-03 30          9
5 Zm00001d000055     B73V4_ctg10     97290    97298 Row-01 12         29
6 Zm00001d000055     B73V4_ctg10     97290    97298 Col-02 22         15
  Gene_length stock
1   NA        D-0081
2   NA        D-0081
3 2873        D-0080
4 2873        D-0080
5 3357        D-0079
6 3357        D-0079

  GeneID             Chromosome Start    End      Sample StartReads EndReads
1 ENSRNA049997441-T1 7          39887977 39887985 Row-01  8          9
2 ENSRNA049997441-T1 7          39887977 39887985 Col-04 28         39
  Gene_length stock
1 NA          D-0081
2 NA          D-0081

   GeneID         Chr         Start     End       Sample InsertionStart
1  Zm00001d027801 1            13815367  13827552 Col-02  13815363
2  Zm00001d027801 1            13815367  13827552 Row-01  13815363
3  Zm00001d028818 1            47566046  47589502 Col-01  47566043
4  Zm00001d028818 1            47566046  47589502 Row-03  47566043
5  Zm00001d028962 1            53030837  53032126 Col-03  53032126
6  Zm00001d028962 1            53030837  53032126 Row-03  53032126
7  Zm00001d029144 1            60427117  60431202 Col-02  60431195
8  Zm00001d029144 1            60427117  60431202 Row-03  60431195
9  Zm00001d022970 1           261786400 261787460 Col-02 261786393
10 Zm00001d022970 1           261786400 261787460 Row-03 261786393
11 Zm00001d033420 1           262569031 262571498 Col-02 262569026
12 Zm00001d033420 1           262569031 262571498 Row-02 262569026
13 Zm00001d034432 1           292893097 292904934 Col-01 292904929
14 Zm00001d034432 1           292893097 292904934 Row-01 292904929
15 Zm00001d034638 1           298677159 298680740 Col-03 298677155
16 Zm00001d034638 1           298677159 298680740 Row-02 298677155
17 Zm00001d024593 10           79588608  79589422 Col-01  79589421
18 Zm00001d024593 10           79588608  79589422 Row-03  79589421
19 Zm00001d024676 10           83290724  83291829 Col-03  83290721
20 Zm00001d024676 10           83290724  83291829 Row-01  83290721
21 Zm00001d024933 10           95587713  95593434 Col-03  95587708
22 Zm00001d024933 10           95587713  95593434 Row-01  95587708
23 Zm00001d004137 2            85731223  85732587 Col-01  85731220
24 Zm00001d004137 2            85731223  85732587 Row-01  85731220
25 Zm00001d004812 2           140809252 140813969 Col-03 140809245
26 Zm00001d004812 2           140809252 140813969 Row-03 140809245
27 Zm00001d006249 2           202837832 202840525 Col-02 202840523
28 Zm00001d006249 2           202837832 202840525 Row-02 202840523
29 Zm00001d041829 3           139490055 139496394 Col-04 139496394
30 Zm00001d041829 3           139490055 139496394 Row-01 139496394
⋮  ⋮              ⋮           ⋮         ⋮         ⋮      ⋮
51 Zm00001d054070 4           245864833 245876851 Col-01 245864832
52 Zm00001d054070 4           245864833 245876851 Row-03 245864832
53 Zm00001d013646 5            16124142  16125803 Col-03  16124139
54 Zm00001d013646 5            16124142  16125803 Row-01  16124139
55 Zm00001d017021 5           182894380 182895386 Col-01 182894374
56 Zm00001d017021 5           182894380 182895386 Row-04 182894374
57 Zm00001d018207 5           216597825 216606598 Col-03 216606593
58 Zm00001d018207 5           216597825 216606598 Row-01 216606593
59 Zm00001d018420 5           220379839 220387369 Col-01 220387364
60 Zm00001d018420 5           220379839 220387369 Row-01 220387364
61 Zm00001d038189 6           150913450 150943935 Col-03 150943934
62 Zm00001d038189 6           150913450 150943935 Row-03 150943934
63 Zm00001d038732 6           163536956 163538558 Col-02 163538551
64 Zm00001d038732 6           163536956 163538558 Row-02 163538551
65 Zm00001d039020 6           168822275 168828891 Col-04 168822272
66 Zm00001d039020 6           168822275 168828891 Row-01 168822272
67 Zm00001d018902 7             8758340   8762850 Col-02   8762848
68 Zm00001d018902 7             8758340   8762850 Row-03   8762848
69 Zm00001d019644 7            47868260  47872065 Col-02  47868258
70 Zm00001d019644 7            47868260  47872065 Row-04  47868258
71 Zm00001d019719 7            53590581  53601030 Col-04  53601027
72 Zm00001d019719 7            53590581  53601030 Row-03  53601027
73 Zm00001d009413 8            63468493  63474399 Col-03  63468486
74 Zm00001d009413 8            63468493  63474399 Row-01  63468486
75 Zm00001d044829 9             4331182   4332060 Col-04   4331175
76 Zm00001d044829 9             4331182   4332060 Row-01   4331175
77 Zm00001d046590 9            97452571  97463456 Col-02  97463450
78 Zm00001d046590 9            97452571  97463456 Row-01  97463450
79 Zm00001d000150 B73V4_ctg75    116649    127114 Col-04    127109
80 Zm00001d000150 B73V4_ctg75    116649    127114 Row-04    127109
   InsertionEnd StartReads EndReads Gene_length
1   13815371     6          9       12186
2   13815371     6          4       12186
3   47566051     4          2       23457
4   47566051     7          4       23457
5   53032134    14         17        1290
6   53032134    35         27        1290
7   60431203    12          6        4086
8   60431203     6          2        4086
9  261786401     3          2        1061
10 261786401     4          2        1061
11 262569034     8          2        2468
12 262569034    23         13        2468
13 292904937     2          2       11838
14 292904937     4          3       11838
15 298677163     3          3        3582
16 298677163    77         18        3582
17  79589429     5         14         815
18  79589429     4         13         815
19  83290729     6          9        1106
20  83290729     8         12        1106
21  95587716    35         21        5722
22  95587716     3          2        5722
23  85731228     6          9        1365
24  85731228     4          4        1365
25 140809253    15         12        4718
26 140809253    30          2        4718
27 202840531     4          2        2694
28 202840531    14         16        2694
29 139496402     4          6        6340
30 139496402     2          3        6340
⋮  ⋮            ⋮          ⋮        ⋮
51 245864840     4          7       12019
52 245864840     2          5       12019
53  16124147    73         77        1662
54  16124147    75         61        1662
55 182894382    27         19        1007
56 182894382     2          4        1007
57 216606601     2          2        8774
58 216606601     3          2        8774
59 220387372    22         12        7531
60 220387372    23         31        7531
61 150943942    13          7       30486
62 150943942     2          2       30486
63 163538559    15          4        1603
64 163538559    16         20        1603
65 168822280     4          4        6617
66 168822280     2          2        6617
67   8762856    11         19        4511
68   8762856     7          8        4511
69  47868266     2          4        3806
70  47868266     2          3        3806
71  53601035    57         44       10450
72  53601035     9          5       10450
73  63468494     7         12        5907
74  63468494     2          3        5907
75   4331183    56         19         879
76   4331183    10          6         879
77  97463458     2          2       10886
78  97463458     2          2       10886
79    127117     3          2       10466
80    127117     3          2       10466